spring.application.name=simpleapp

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d72flg9r0fns73ealvt0-a.oregon-postgres.render.com:5432/test_instance_zusc
spring.datasource.username=root
spring.datasource.password=F40DXjhdKIL0ZFFaInS2vW8guKhvh6jg
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port (Render dynamic port)
server.port=${PORT:8080}